version: "3.8"
services:
  # Nombre del servicio
  app:
    # Info para la contruccion de la imagen
    build:
      context: .
      # Dockerfile con las instrucciones de contrucci贸n de la imagen de la app usando de base de la imagen php:8.2-fpm-alpine
      dockerfile: ./php/Dockerfile
    # Nombre del contenedor
    container_name: tecno_app
    restart: "no"
    volumes:
      # Redefinici贸n del puerto de la imagen php:8.2-fpm-alpine 
      - ./php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      # Configuraci贸n del php-fpm
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    # Extension de la configuracion del servicio
    extends:
      # Nombre del archivo del que extendera el servicio
      file: ./php/volumes.yml
      # Nombre del servicio del que extiende
      service: app_volumes
    # Servicios que se deben iniciar antes que tecno_app
    depends_on:
      - mariadb

  # Nombre del servicio
  nginx:
    # Imagen base del servicio
    image: nginx:1.25.2-alpine
    # Nombre del contenedor
    container_name: tecno_nginx
    restart: "no"
    # Configuracion de puertos de acceso host:container_network
    ports:
      - "8181:80"
      - "447:443"
    volumes:
      # Configuraci贸n de los servidores web de nginx
      - ./nginx/myphpwebsite.conf:/etc/nginx/conf.d/default.conf
      # Configuracion principal nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      # LLaves y certificados para el https
      - ./nginx/certs/server.crt:/etc/nginx/ssl/server.crt
      - ./nginx/certs/server.key:/etc/nginx/ssl/server.key
      - ./nginx/certs/laravel.crt:/etc/nginx/ssl/laravel.crt
      - ./nginx/certs/laravel.key:/etc/nginx/ssl/laravel.key

  mariadb:
    # Imagen base del servicio
    image: mariadb:lts
    container_name: tecno_mariadb
    # Configuracion de puertos de acceso host:container_network
    ports: 
      - "3309:3306"
    environment:
      # Configuracion de variables de entorno de mariadb
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=dbtecno2023

  phpmyadmin:
    image: phpmyadmin:apache
    container_name: tecno_phpmyadmin
    # Configuracion de puertos de acceso host:container_network
    ports:
      - "9090:80"
    environment:
      # Configuracion de variables de entorno para la conexion con el servicio de mariadb
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - PMA_ARBITRARY=1
    # Servicios que se deben iniciar antes que tecno_phpmyadmin
    depends_on:
      - mariadb